// Auto-generated by write-build-meta.mjs - DO NOT EDIT
export const BUILD_NUMBER = 21;
export const BUILD_BRANCH = 'main';
export const BUILD_COMMIT = 'a368367';
export const BUILD_TIMESTAMP = '2025-11-15T20:34:04.328Z';
export const BUILD_DOMAIN = '';
