// Auto-generated by write-build-meta.mjs - DO NOT EDIT
export const BUILD_NUMBER = 145;
export const BUILD_BRANCH = 'main';
export const BUILD_COMMIT = 'ab0438f';
export const BUILD_TIMESTAMP = '2025-12-08T14:19:39.576Z';
export const BUILD_DOMAIN = '';
