// Auto-generated by write-build-meta.mjs - DO NOT EDIT
export const BUILD_NUMBER = 152;
export const BUILD_BRANCH = 'main';
export const BUILD_COMMIT = '53fa5d3';
export const BUILD_TIMESTAMP = '2025-12-09T16:33:56.513Z';
export const BUILD_DOMAIN = '';
