-- Create ebay_orders table matching SQLAlchemy model
CREATE TABLE IF NOT EXISTS public.ebay_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id VARCHAR(100) NOT NULL,
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    ebay_account_id VARCHAR(36),
    ebay_user_id VARCHAR(100),
    creation_date TIMESTAMPTZ,
    last_modified_date TIMESTAMPTZ,
    order_payment_status VARCHAR(50),
    order_fulfillment_status VARCHAR(50),
    buyer_username VARCHAR(100),
    buyer_email VARCHAR(100),
    buyer_registered VARCHAR(100),
    total_amount NUMERIC(14, 2),
    total_currency VARCHAR(10),
    order_total_value NUMERIC(14, 2),
    order_total_currency VARCHAR(10),
    line_items_count INTEGER,
    tracking_number VARCHAR(100),
    ship_to_name VARCHAR(100),
    ship_to_city VARCHAR(100),
    ship_to_state VARCHAR(100),
    ship_to_postal_code VARCHAR(50),
    ship_to_country_code VARCHAR(10),
    order_data JSONB,
    raw_payload JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_ebay_orders_order_id_user_id UNIQUE (order_id, user_id)
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_ebay_orders_creation_date ON public.ebay_orders (creation_date);
CREATE INDEX IF NOT EXISTS idx_ebay_orders_ebay_account_id ON public.ebay_orders (ebay_account_id);
CREATE INDEX IF NOT EXISTS idx_ebay_orders_order_id ON public.ebay_orders (order_id);
CREATE INDEX IF NOT EXISTS idx_ebay_orders_user_id ON public.ebay_orders (user_id);
CREATE INDEX IF NOT EXISTS idx_ebay_orders_buyer_username ON public.ebay_orders (buyer_username);
CREATE INDEX IF NOT EXISTS idx_ebay_orders_order_status ON public.ebay_orders (order_payment_status);

-- Migrate data from TEMP_ebay_orders if it exists
DO $$
BEGIN
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'TEMP_ebay_orders') THEN
        INSERT INTO public.ebay_orders (
            order_id, user_id, 
            ebay_account_id, ebay_user_id,
            creation_date, last_modified_date,
            order_payment_status, order_fulfillment_status,
            buyer_username, buyer_email,
            tracking_number, 
            ship_to_name, ship_to_city, ship_to_state,
            ship_to_postal_code, ship_to_country_code,
            raw_payload,
            created_at, updated_at
        )
        SELECT 
            order_id, user_id::uuid, 
            ebay_account_id, ebay_user_id,
            creation_date::timestamptz, last_modified_date::timestamptz,
            order_payment_status, order_fulfillment_status,
            buyer_username, buyer_email,
            tracking_number, 
            ship_to_name, ship_to_city, ship_to_state,
            ship_to_postal_code, ship_to_country_code,
            raw_payload::jsonb,
            NOW(), NOW()
        FROM public."TEMP_ebay_orders"
        ON CONFLICT (order_id, user_id) DO NOTHING;
        
        RAISE NOTICE 'Migrated data from TEMP_ebay_orders';
    END IF;
END $$;
