-- Add raw_openai_response to accounting_bank_statement
ALTER TABLE public.accounting_bank_statement 
ADD COLUMN IF NOT EXISTS raw_openai_response JSONB;

-- Create accounting_process_log table
CREATE TABLE IF NOT EXISTS public.accounting_process_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_statement_id BIGINT REFERENCES public.accounting_bank_statement(id) ON DELETE CASCADE,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    level TEXT NOT NULL DEFAULT 'INFO', -- 'INFO', 'WARNING', 'ERROR'
    message TEXT NOT NULL,
    details JSONB
);

CREATE INDEX IF NOT EXISTS idx_accounting_process_log_stmt_id ON public.accounting_process_log(bank_statement_id);
